yarn run v1.12.3
$ node index.js
Sat, 02 Nov 2019 11:14:17 GMT koa deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/blob/master/docs/migration.md at index.js:62:4
Terminated
yarn run v1.12.3
$ node index.js
Sat, 02 Nov 2019 11:32:14 GMT koa deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/blob/master/docs/migration.md at index.js:62:4
Error: Service returned error: 429 Too Many Requests. You have exceeded your rate limit.
    at submitClocking (/home/asus/intratime/intratime.js:102:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:11802) UnhandledPromiseRejectionWarning: ReferenceError: userId is not defined
    at registerCommand (/home/asus/intratime/features/register.js:90:36)
    at processMessage (/home/asus/intratime/features/index.js:38:28)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:11802) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:11802) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:11802) UnhandledPromiseRejectionWarning: ReferenceError: userId is not defined
    at registerCommand (/home/asus/intratime/features/register.js:90:36)
    at processMessage (/home/asus/intratime/features/index.js:38:28)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:11802) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
Terminated
